"""add document_records

Revision ID: aa5a11fddc4d
Revises: 
Create Date: 2026-05-14 09:48:49.322860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa5a11fddc4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('minio_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_records_id'), 'document_records', ['id'], unique=False)
    op.create_table('task_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_records_id'), 'task_records', ['id'], unique=False)
    op.create_index(op.f('ix_task_records_status'), 'task_records', ['status'], unique=False)
    op.create_index(op.f('ix_task_records_task_id'), 'task_records', ['task_id'], unique=True)
    op.create_index(op.f('ix_task_records_task_type'), 'task_records', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_records_task_type'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_task_id'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_status'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_id'), table_name='task_records')
    op.drop_table('task_records')
    op.drop_index(op.f('ix_document_records_id'), table_name='document_records')
    op.drop_table('document_records')
    # ### end Alembic commands ###
